# Generated by Django 4.1.3 on 2022-11-17 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=7)),
                ('video_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('likes_count', models.PositiveBigIntegerField()),
                ('dislike_count', models.PositiveBigIntegerField()),
                ('view_count', models.PositiveBigIntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ychanels_analitics.video')),
            ],
        ),
    ]
