# Generated by Django 4.1.3 on 2022-11-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ychanels_analitics', '0002_remove_video_video_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='dislike_count',
            new_name='dislikes_count',
        ),
    ]
