# Generated by Django 4.1.3 on 2022-12-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ychanels_analitics', '0003_rename_dislike_count_analytics_dislikes_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='uploader_subscriber_count',
            new_name='comment_count',
        ),
    ]
