# Generated by Django 4.1.4 on 2022-12-11 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ychanels_analitics', '0005_channel_channelanalytics_video_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelanalytics',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 17, 1, 39, 818537, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
